style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
